version: "3.9"

services:
  goalfy-data-connect-sql:
    build: .
    depends_on:
      - postgres
      - redis
      - kafka
    ports:
      - "8081:8080"
    environment:
      APP_ENVIRONMENT: development
      APP_LOG_LEVEL: debug
      KAFKA_BROKERS: kafka:9092
      REDIS_ADDR: redis:6379
      POSTGRES_DSN: postgres://goalfy:goalfy@postgres:5432/goalfy_connect?sslmode=disable
      SECRET_PROVIDER: env
      SECRET_PREFIX: "SECRET_"
      # Example external source secret (used by PasswordRef = "MY_SOURCE")
      SECRET_MY_SOURCE: goalfy
      POSTGRES_HOST_AUTH_METHOD: trust
      HTTP_PORT: 8080
    restart: on-failure

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: goalfy
      POSTGRES_PASSWORD: goalfy
      POSTGRES_DB: goalfy_connect
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  pgdata:
